### ISSUE TITLE
Borders are not rounded in focus and error states in Safari

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-combobox#106]
## Describe the bug

The border corners of the element are not rounded in Safari when the element is in a focus or error state.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/combobox
1. Click on any example
1. See error

## Expected behavior

Border corners are rounded.

## Desktop (please complete the following information):

 - Browser: Safari

## Additional context

This is a bug for all of our form elements, refer to this initial ticket opened in `auro-input`:
- https://github.com/AlaskaAirlines/auro-input/pull/208

**Comment by blackfalcon** [comment]
Seeing that @jdeeezzy self-assigned and this issue has not gone through tech'refinement, I am assuming that there was a hand-off between @jordanjones243 and @jdeeezzy  and am removing the `not-reviewed` label.

**Comment by blackfalcon** [comment]
Reviewed in Safari, this appears to not be an issue. Not sure why this is still open or there is no reference to a PR? Will follow up with @jdeeezzy to address process.
