### ISSUE TITLE
error state is dropped once an option is chosen, but error UI persists

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-combobox#111]
## Describe the bug

When a combobox has an `error` attribute and then a user selects an option, the error attribute is dropped, but the error UI still shows on the component.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/combobox/api#gsc.tab=0
1. Scroll down to `error` example
1. Give focus to the combobox
2. Type `a`
3. Select "apples"

## Expected behavior

Both the `error` attribute and error in the UI persist after a user selects an option.

## Screenshots

<img width="488" alt="Screen Shot 2023-01-06 at 2 29 14 PM" src="https://user-images.githubusercontent.com/55807669/211110633-a90d055a-fc89-4485-a231-8811f83d46c0.png">

**Comment by blackfalcon** [comment]
This is not actually a bug. The example in the doc site is showing a persisted error state set by the user and is only to be controlled by the user when used. We are not to over-ride that state. 

But...

This example shows and it was verified that there is a bug that we are overriding the error string. We should not see `null` in the UI, but see the custom error message. 

## Exit criteria 

This issue will be considered complete once the persisted error state is shown in the UI regardless of user interaction.
