### ISSUE TITLE
Document how-to highlight option

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-combobox#112]
# General Support Request

Update element documentation to illustrate a how-to feature for auro-combobox that will allow a user to highlight an option in the menu.

## Support request

This work is aligned with the updates to auro-menu, but slightly updated to illustrate this feature with combobox specifically. 

## Context

See supporting issue 

- https://github.com/AlaskaAirlines/auro-menu/issues/169

**Comment by jordanjones243** [comment]
Moving this to "Triage" as this ticket needs more clarification

**Comment by Patrick-Daly-AA** [comment]
This is gated to be completed with the related work on Auro-Menu
