### ISSUE TITLE
Improve dynamic menu example

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-combobox#117]
## Describe the bug

In the dynamic menu options example, there are two bugs:
- When there is text within the combobox and there are no matching options, the example shows an empty bib
- When the contents of the combobox are then deleted, an error coming from the Javascript of this example is thrown in the console

## To Reproduce

1. Run the localhost of combobox and find the "Dynamic Menu Example" on the API page
1. Click within the combobox in the example
1. Type "as" into the combobox
1. See 1st error
2. Delete the contents of the combobox via keyboard
3. Open the browser's Javascript console
4. See 2nd error

## Expected behavior

The example should reflect a combobox with a dynamically changing menu, without errors in the UI or console

## Screenshots

1st error:
![Screen Shot 2023-02-02 at 5 12 48 PM](https://user-images.githubusercontent.com/55807669/216487356-c39de3a1-3651-45c6-9a12-5accaca41b36.png)

2nd error:
![Screen Shot 2023-02-02 at 5 11 15 PM](https://user-images.githubusercontent.com/55807669/216487379-e1cd1fb1-5e2d-479c-9ede-bfcc3f22b64e.png)

**Comment by Patrick-Daly-AA** [comment]
Investigation needed into the root cause, after getting unblocked by other docsSite rendering issues.
