### ISSUE TITLE
Airports example filter is broken

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-combobox#119]
## Describe the bug

When using the "Airports example" on the docsite, the menu options are not being filtered when adding text into the input.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/combobox
1. Navigate to the Airports example
1. Type "M" into the input
1. See error

## Expected behavior

Only the menu options with matching characters from the input text should be shown.

## Screenshots

![Screen Shot 2023-02-13 at 12 03 01 PM](https://user-images.githubusercontent.com/55807669/218562771-0bcdb11e-10d0-46e6-99f9-204b115c3f91.png)

## AC

This bug seems to only be happening in the Airports example.

**Comment by Patrick-Daly-AA** [comment]
This is working as expected.  There is a suggested airport in the list that contains the letter "M"
