### ISSUE TITLE
No matching option text not showing in bib

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-combobox#120]
## Describe the bug

When there are no matching menu options after a user inputs text, an empty bib is shown, when there should be text saying "No matching option". 

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/combobox
1. Navigate to the Basic example
1. Type "M" into the input
1. See error

## Expected behavior

The dropdown should display the next "No matching option" when there are no matching menu options.

**Comment by blackfalcon** [comment]
@leeejune is there a design spec for this?

**Comment by leeejune** [comment]
@blackfalcon nope, no design specs.

**Comment by blackfalcon** [comment]
I created a new design story to look into this feature 

- https://github.com/AlaskaAirlines/auro-combobox/issues/123

**Comment by jason-capsule42** [comment]
Changing from `feature` to `bug` as this API feature already exists, it just doesn't work and we _might_ choose to style it differently in the future.

**Comment by Patrick-Daly-AA** [comment]
Putting in investigating to see if there is a slot for "no matching options" text (We suspect that there isn't one).

Next steps will be to create that slot and consult with design on having a potential for a default value.

**Comment by Patrick-Daly-AA** [comment]
Update: this is a bug.  It needs fixing.
