### ISSUE TITLE
Design empty or waiting bib UI

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-combobox#123]
## Is your feature request related to a problem? Please describe.

There are cases where the dynamic data returning to the bib from an external call is a wait. Currently, there is no UI to support this and a dead/empty bib is revealed. 

## Describe the solution you'd like

Design a solution that we can use for these states. 

## Exit criteria 

This issue will be complete once an agreed-upon FIGMA update to the blueprint that engineering can follow.

**Comment by leeejune** [comment]
Consulted UX writers for appropriate text: 

> "This location doesn't match any airports in our network. Please try another."

**Comment by blackfalcon** [comment]
@leeejune can you update the figma docs to illustrate this?

**Comment by jordanjones243** [comment]
This issue was fixed by this piece of work and can be closed:
- https://github.com/AlaskaAirlines/auro-combobox/pull/159/files
