### ISSUE TITLE
jsdoc/no-undefined-types warning appears in CLI

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-combobox#143]
## Describe the bug

Seeing the following in the CLI when performing a build

```
/Users/dalesande/src/auro/combobox/src/auro-combobox.js
  38:1  warning  The type 'auroCombobox-ready' is undefined     jsdoc/no-undefined-types
  39:1  warning  The type 'auroCombobox-valueSet' is undefined  jsdoc/no-undefined-types

✖ 2 problems (0 errors, 2 warnings)
```

Both these functions are labeled as `@private`, If they are private, then they do not need to be listed on lines 38 and 39 for the creation of public docs. 

## Exit criteria 

Post update the warning is no longer reported in the CLI.

**Comment by jordanjones243** [comment]
This ticket is being moved to "Blocked" until this PR is released and the button dependency is updated:
- https://github.com/AlaskaAirlines/auro-button/pull/246
