### ISSUE TITLE
`api.min.js` prints errors in console during dynamic menu demo

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/auro-combobox#150]
### Please verify the version of auro-combobox you have installed

1.7.8

### Please describe the bug

1. Go to `api.html` page
1. Go to "Dynamic Menu" demo
2. Enter text in menu and delete it all
3. Observe the following error in the console: 
<img width="1764" alt="image" src="https://github.com/AlaskaAirlines/auro-combobox/assets/23248722/bc4f043c-5ccb-418a-91b0-13c17a5b5672">

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

No errors print to the console

### Additional context

This does not seem to be impacting the functionality of the combobox but will make validating its functionality easier in the future.

**Comment by jason-capsule42** [comment]
I am closing this ticket as it is no longer an issue after the latest updates to get all components updated to the latest JS example standard. I have verified this is not an issue on the live docsite as well as in the localhost.
