### ISSUE TITLE
Add a example setting value programmatically

### ISSUE THREAD

**Issue by sadekcbenjamin** [AlaskaAirlines/auro-combobox#152]
### General Support Request

- add an example on how to programmatically update the combobox//input values because the examples on the documentation page only show how to change the value using buttons. 

- The input component "change value for examples do not work 

https://auro.alaskaair.com/components/auro/input#gsc.tab=0

**Comment by jordanjones243** [comment]
This ticket is being moved to "Blocked" until this PR is released and the button dependency is updated:
- https://github.com/AlaskaAirlines/auro-button/pull/246
