### ISSUE TITLE
Updating test runner breaks tests

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-combobox#160]
### Please verify the version of auro-combobox you have installed

@latest

### Please describe the bug

When updating `@web/test-runner devDep  0.16.1  ❯  0.18.0`

```shell
 ❌ auro-combobox > handles the required state being set
      AssertionError: expected null to equal 'valueMissing'
        at n.<anonymous> (test/auro-combobox.test.js:359:53)

Chrome: |██████████████████████████████| 1/1 test files | 21 passed, 1 failed
```

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

All tests should not fail with updated version of test runners.

### Additional context

This issue appears to be directly related to a root issue with auro-input

- https://github.com/AlaskaAirlines/auro-input/issues/279
- https://github.com/AlaskaAirlines/auro-datepicker/issues/183

### Exit criteria

This issue can be closed once the root cause has been addressed and all tests run with updated test runners.

**Comment by jason-capsule42** [comment]
This will be addressed as part of the new auro-form repository work. Closing out as won't do any work here in this repository.
