### ISSUE TITLE
Icons are not rendering for examples

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-combobox#161]
### Please verify the version of auro-combobox you have installed

1.9.1

### Please describe the bug

1. Go to https://auro.alaskaair.com/components/auro/combobox
2. Scroll to "Swapping Values Between Comboboxes" example
3. See error

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

The `auro-icon` could render

### What browsers are you seeing the problem on?

Chrome

### Exit criteria

Icons render in examples as expected

**Comment by Patrick-Daly-AA** [comment]
Blocked waiting on fix for this issue: https://github.com/AlaskaAirlines/auro-button/issues/245
