### ISSUE TITLE
Build failed due to invalid popper.js ref

### ISSUE THREAD

**Issue by megrenn** [AlaskaAirlines/auro-combobox#197]
From Joe Chin: 
"I'm getting this "module build failed" when I try to use auro-combobox in my project. It appears to be referencing popper.js incorrectly? Any suggestions? Thank you."

![Image](https://github.com/user-attachments/assets/1a0828af-b297-43fe-9e47-7bd6a63990ec)

https://teams.microsoft.com/l/message/19:5df2ca021a6548c4af54256bbc737129@thread.skype/1730156416279?tenantId=0f44c5d4-42b0-45c2-bf55-d0fea8430d33&groupId=3a6a4783-59c6-496a-a20c-ab306461a894&parentMessageId=1730156416279&teamName=All%20E-commerce&channelName=Auro%20(public)&createdTime=1730156416279

**Comment by jason-capsule42** [comment]
This is actually already fixed in dropdown and combobox just needs to be updated to use the latest version of dropdown.
