### ISSUE TITLE
Add a borderless style attribute

### ISSUE THREAD

**Issue by jeremeevans** [AlaskaAirlines/auro-combobox#39]
## Is your feature request related to a problem? Please describe.

The auro-combobox does not have a borderless style, so it looks bad when it is combined with other auro components when using borderless styling.

## Describe the solution you'd like

Add a borderless attribute so it's design can match other auro components

## Describe alternatives you've considered

Limiting designs that use auro to only ever use bordered components.

## Additional context

<img width="827" alt="image" src="https://user-images.githubusercontent.com/1747006/172652547-3e26102f-16ea-4da8-9b2a-db74c6ad3de1.png">

**Comment by leeejune** [comment]
Yes! I would love to support. Please let me know who the designer is and I will reach out to them.

**Comment by leeejune** [comment]
Currently our design direction is moving towards the bordered input styles because of a few accessibility concerns we had with the borderless style. Designers are encouraged to use the bordered input styles as well. If we ever add the borderless style combobox, I'll make sure it is well announced! :)

**Comment by jeremeevans** [comment]
James Tsai recently took over design for our team; this particular page is not part of an official design, it's more of an energy point for testing. That being said, I much prefer the cleaner aesthetic of the borderless style.

Jereme

-------- Original Message --------
