### ISSUE TITLE
Add the ability to set the error text

### ISSUE THREAD

**Issue by jeremeevans** [AlaskaAirlines/auro-combobox#40]
## Is your feature request related to a problem? Please describe.

Auro Input allows one to set the error text. Auro Combobox only allows one to set whether or not to persistently show a generic message.

## Describe the solution you'd like

Expose the error message as a property that can be set.

## Describe alternatives you've considered

Not use this control

**Comment by blackfalcon** [comment]
Removed assigned devs and updated status to be middle of the backlog. There is an opportunity to make this easier, but there is nothing blocking use as it is right now based on the [current API](https://auro.alaskaair.com/components/auro/combobox/api#error:~:text=See%20code-,Slot%20Examples,-HelpText)

**Comment by blackfalcon** [comment]
This issue will be replaced with a new issue that better describes the actual work.
