### ISSUE TITLE
Address focus-visible state in demo page

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-combobox#44]
## Describe the bug

The demo page of this element no longer supports a `focus-visible` UI state due to updates to WCSS. But what is also interesting is that the polyfill for focus-visible still appears to be operating on the page? Where is that coming from and why? 

## To Reproduce
1. Run the `auro-combobox` element locally
2. Go to the demo page
3. Tab through the UI

## Expected behavior

No polyfill should be operating and the `focus-visible` UI should appear when tabbing to an element. 

## Additional context

- https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/118

**Comment by jason-capsule42** [comment]
This will be resolved when this WCSS ticket is fixed: https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/118
