### ISSUE TITLE
Missing demo for combobox with menu

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-combobox#47]
# General Support Request

Looking around the Auro docsite we are missing a demo using combobox with auro-menu options to select from. 

## Support request

There is an example of typing into the combobox and getting a smaller list, but there are no examples for how this would be used in the scenario for displaying all menu options when clicking on the trigger. 

## Possible Solution

Add a demo to illustrate this use case.

**Comment by braven112** [comment]
Maybe we should add some notes about do's and don't and loop in @leeejune

**Comment by blackfalcon** [comment]
This was quickly discussed and the result was that an additional demo is not needed.
