### ISSUE TITLE
Checkbox missing on selected menu option

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-combobox#53]
## Describe the bug

Menu is missing checkbox for selected option.

## To Reproduce

1. Go to combobox.
2. Type and select an option.
3. Click out.
4. Click on the trigger.
5. See missing checkbox.

## Expected behavior

There should be a checkbox next to the selected option as an indication of a selection.

**Comment by braven112** [comment]
@leeejune I don't think we need this anymore can you confirm?

**Comment by leeejune** [comment]
@braven112 Yup we don't need it anymore!
