### ISSUE TITLE
First load combobox menu is miss-aligned

### ISSUE THREAD

**Issue by jesussilverioea** [AlaskaAirlines/auro-combobox#54]
## Describe the bug
We implemented the combobox with a dynamic menu after which whenever one types the first character the menu seems miss-aligned (See picture). We believe it is something to do with the firstUpdate() function not loading the style properly.

## To Reproduce

1. Go to https://www.alaskaair.com/search-test/
1. Click on 'From or To'
1. Type only one character
1. See the menu miss align. AFTER clicking on the box again or typing another character IT WILL align again.

## Screenshots
<img width="436" alt="Screen Shot 2022-07-28 at 8 53 49 AM" src="https://user-images.githubusercontent.com/108018885/182676606-28b7753c-2128-4666-b8fc-bdb9aa1d2b77.png">

## Additional context

[Our Code](https://github.com/Alaska-ECommerce/flightsearch-lem-svelte/blob/main/src/lib/planbook/CitiesDates.svelte#L84)
[This change](https://github.com/AlaskaAirlines/auro-combobox/blob/main/src/auro-combobox.js#L132) was implemented in order to let us handle the menu options dynamically.

**Comment by braven112** [comment]
@jesussilverioea Were you able to find a way to fix this one?  I noticed this issue last week but I can't reproduce it anymore.

**Comment by jesussilverioea** [comment]
We were able to find a solution for this one. I'm closing this item.
