### ISSUE TITLE
Required* Combobox fields error prior to entering anything

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-combobox#61]
## Describe the bug
Required combobox fields error on a click into the field and click out, prior to any text being entered. This feels like bad practice to error on the user prior to even attempting to enter any text as they might just be directing their attention elsewhere temporarily.

![image](https://user-images.githubusercontent.com/34354487/184991250-5e3c7e44-b036-4400-97f6-a6fa6c641022.png)

## To Reproduce

1. Go to https://www.alaskaair.com/search-test/
2. Click into 'To' combobox
3. Click out of 'To' combobox

## Expected behavior

I don't expect the required combobox to error until the user has entered text into the field OR submitted the form without entering any text into the field.

## Screenshots

![image](https://user-images.githubusercontent.com/34354487/184991885-094cf34b-d53d-482c-ada5-6871a16d0674.png)

**Comment by blackfalcon** [comment]
I can't say that this is a bug? That is working as designed. If a user entered a required field and exited that field and the value is still empty, then it should error. You will find this to be a constant with all other input elements and the `required` attribute. 

https://auro.alaskaair.com/components/auro/input

**Comment by blackfalcon** [comment]
Accidentally added to other PR, no work has been done about this issue. 

Labeling as abandoned as the reported bug is expected behavior. If there is to be a change to this behavior, please include @leeejune to discuss the i/o error state management and the expected UX.
