### ISSUE TITLE
First character entry after selection clears input box instead of entering

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-combobox#71]
## Describe the bug
Entering a character after selecting all text within the input box clears the text, but does not input the entered character.

## To Reproduce

1. Go to https://www.alaskaair.com/search-test/
2. Search for an airport in either of the "Cities & dates" comboboxes and make a selection
3. Click on the same combobox to select all text
4. Enter a character
5. See that the character clears the box but is not inputted

## Expected behavior
Entering a character after selecting all text within the input box should clear the input while inputting the character.

## Desktop (please complete the following information):

 - OS: MacOS
 - Browser: Chrome
 - Version: 105.0.5195.102

## Additional context
- The bug does not appear on auro-combobox versions prior to 1.5.1
- Fix is needed before flight search microsite launch on September 21st

**Comment by blackfalcon** [comment]
Verified reported bug.

**Comment by braven112** [comment]
@arrenkhl Are you still having this issue?  I tried to repro it just now and it seems to be working as you are expecting.

**Comment by arrenkhl** [comment]
@blackfalcon @braven112 not seeing this anymore either, I'll go ahead and close this issue.

**Comment by blackfalcon** [comment]
I am bringing this issue back. I spoke with @aesthetiques and there is a possibility that we are not able to repro this issue in their test environment is because there is a local work-around. 

I am waiting on @aesthetiques to help us understand this issue more.

**Comment by blackfalcon** [comment]
Unable to repro.
