### ISSUE TITLE
All doc site examples are broken 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-combobox#72]
## Describe the bug

None of the examples in the doc site illustrate the chosen option when selected. 

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/combobox
1. Go to any example and get a bib/menu to appear
1. Select option from menu
1. See error

## Expected behavior

Selected option should appear in the trigger of the element.

**Comment by jordanjones243** [comment]
Fixed by this PR: https://github.com/AlaskaAirlines/auro-combobox/pull/76
