### ISSUE TITLE
No Matching Options not shown while typing

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-combobox#73]
## To Reproduce

1. Go to the demo page and any example
1. Type some garbage characters into the input
1. See that the bib doesn't show the no matching option string
1. Click away from the combobox
1. Click back into the combobox
1. See that the bib shows the no matching option string

## Expected behavior

No match string should display while typing as appropriate

**Comment by blackfalcon** [comment]
Recent updates to input and combobox have resolved this issue. No longer reproduceable.
