### ISSUE TITLE
Feature Request - TAB acts as Selecting

### ISSUE THREAD

**Issue by isaiahscheel** [AlaskaAirlines/auro-combobox#77]
## Is your feature request related to a problem? Please describe.
- Unknown priority until design gets back. But guessing low at the moment.
- Tabbing moves on from the auro-combo box but does not select anything
- This is causing confusion with power users/testers that tab through the planbook and expect whatever is hovered to be selected when they tab
- In legacy we have seen that hitting TAB either selects the first item in the list if it does not match an exact item. Like typing "SE" then TAB will select "Seattle (All Airports)" the first item in the list. However, typing "SEA" then TAB will select "SEA - Seattle, WA - Seattle/Tacoma" which is an exact match to when they hit TAB
- This feature request may be similar to, but not the same as https://github.com/AlaskaAirlines/auro-combobox/issues/57 

## Describe the solution you'd like

- We would like TAB to act similar to selecting and select the item that the text matches or the first item 
- Maybe we can touch base with designers and see if they want the first item or the most closely related item similar to Issue 57

## Describe alternatives you've considered

- We were going to see what we can do on our side and make tab select whatever is hovered maybe
- We have not looked a ton into it and thought for power users and accessibility that TAB should also select something in the combobox since not selecting something from the dropdown causes it to be "not filled out" because there is only test, not an item selected

## Additional context

- Feel free to play around on https://www.alaskaair.com/search

**Comment by blackfalcon** [comment]
We will have to review this and discuss it. The current functionality for the airport selection changing value as you move through the menu options is actually inconsistent with how many menus operate. See [shoelace](https://shoelace.style/components/select) and [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option).

You will see that while you can tab into the element, moving up/down the list does NOT change the value of the input or select any option. Also, tabbing does nothign with the native element, but exits (without selection) the Shoelace element.

The question is... is this really something we should support? Given that this is inconsistent, how does this effect accessibility?

**Comment by jesussilverioea** [comment]
I think this is an option that we should support. Currently that is implemented in Legacy. Multiple users that navigate the site by "tabbing around" have mentioned this issue.

**Comment by blackfalcon** [comment]
See 

- https://github.com/AlaskaAirlines/auro-combobox/issues/57#issuecomment-1332554544

Meeting scheduled to discuss options.

**Comment by jason-capsule42** [comment]
While I understand legacy supports this feature I am not convinced that we should. Tab (blur) to select is not part of the HTML5 select element API.

I think we should mirror keyboard WCAG behavior as closely as possible.

See this working example for an HTML5 select element: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by blackfalcon** [comment]
Rescheduled team refinement whereas the expected outcome is to create a new feature issue moving forward given the information provided and the information collected in subsequent meetings. Steps to follow:

1. Create a new issue with feature specification and exit criteria 
2. Link back to this originating issue 
3. Close the originating issue

**Comment by jason-capsule42** [comment]
Assigning to @blackfalcon to followup with @jesussilverioea about what we should do here.

**Comment by blackfalcon** [comment]
Moving this issue to the backlog. There are future refactors scheduled for this element where this issue may be addressed.

**Comment by Patrick-Daly-AA** [comment]
Closing as will not do.
