### ISSUE TITLE
Focus + up|down arrow keys should open the bib.

### ISSUE THREAD

**Issue by isaiahscheel** [AlaskaAirlines/auro-combobox#78]
## Is your feature request related to a problem? Please describe.
- Low Priority 
- While tabbing through input fields and selecting something from the combobox, continuing on, then shift+tabbing back, the bib does not open when using up/down arrows
- Selecting something (the from): 
![image](https://user-images.githubusercontent.com/40191651/188994702-5531a53e-dfc2-4afb-81eb-26aec5528782.png)
- And then shift+tabbing back to it: 
![image](https://user-images.githubusercontent.com/40191651/188994755-0ea79561-2fb2-4321-bec2-862e9855b9cc.png)

## Describe the solution you'd like
- Shift+tabbing back to a combobox and using arrows, it open the bib and shows the items 
![image](https://user-images.githubusercontent.com/40191651/188994975-9c53452f-d96e-4c9f-88bf-5ed99ef95c03.png)
- This is similar to how the homewidget works: 

Just shift+tabbed to from :
![image](https://user-images.githubusercontent.com/40191651/188995618-c019f769-6ef8-46a2-8d07-6080dc227b66.png)
Used down arrow to open bib: 
![image](https://user-images.githubusercontent.com/40191651/188995661-575a471c-5ab6-4dd6-957b-c09f7ad01412.png)

## Describe alternatives you've considered
- No alternatives have been considered, if there is any recommendations we can definitely take a look! 

## Additional context
- Can be reproduced here: https://www.alaskaair.com/search

**Comment by blackfalcon** [comment]
Thanks! We will get this in the hopper.

**Comment by jason-capsule42** [comment]
Arrow keys are not currently part of the combobox (or select) behavior for opening the dropdown.

This would be a new feature, rather than a bug.

**Comment by blackfalcon** [comment]
Agreed, this is not currently supported and should not be included in the `bug bash`, but treated as a potential new feature to be released. 

We need to evaluate whether or not this complies with the current standard use of a `combobox` and how we would potentially support this.

**Comment by blackfalcon** [comment]
See 

- https://github.com/AlaskaAirlines/auro-combobox/issues/57#issuecomment-1332554544

**Comment by jason-capsule42** [comment]
This behavior is part of the HTML5 select element support. I think we should consider adding this to both auro-select and auro-combobox.

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
