### ISSUE TITLE
UI bug text in the input

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-combobox#81]
## Describe the bug
When a combobox is filled out the text is cut off prematurely on the right when not in focus.  
![image](https://user-images.githubusercontent.com/5118118/190838676-7bd82785-7b6f-42a9-937a-3d156c96e912.png)

## To Reproduce

1. Go to '[here](https://www.alaskaair.com/search-test/)'
1. Fill out the airport search
1. Pick a longer airport name
1. Change focus

## Expected behavior

Or if not in focus it should look something like this:
![image](https://user-images.githubusercontent.com/5118118/190838762-fc4f525f-bd99-42f3-b500-23633cacb21d.png)

**Comment by jason-capsule42** [comment]
This will be fixed by this auro-input ticket: https://github.com/AlaskaAirlines/auro-input/pull/192

**Comment by blackfalcon** [comment]
This issue was closed out by the following work

- https://github.com/AlaskaAirlines/auro-input/pull/193
