### ISSUE TITLE
auro-combobox height doesn't match other form elements

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-combobox#82]
## Describe the bug

Currently auro-combobox is 60px tall.  All the other auro form elements are 58px.

## To Reproduce

1. Go to '[here](https://auro-examples.vercel.app/forms)'
1. View the examples

## Expected behavior

The height of auro-combobox is 58px like all the other elements.  This height should also be consistent in all states

## Screenshots

![image](https://user-images.githubusercontent.com/5118118/191341694-31471437-2cc3-4ac1-b047-7971c8e67d98.png)

## Additional context

I'm not certain this would be the ultimate fix but it does seem like combobox is inheriting a version of auro-input that has a 2px bottom border.
![image](https://user-images.githubusercontent.com/5118118/191342002-9ab05d45-6153-4ade-9764-d335ca7270e5.png)

Adjusting the border bottom width value to 0 would be one way to fix it.

**Comment by jason-capsule42** [comment]
These changes are broken in combobox with the latest version of auro-input.
