### ISSUE TITLE
The CLEAR `x` button no longer works

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-combobox#92]
The CLEAR `x` button no longer works. You don't see my pointer but look for the blinking colored outline. That is me clicking the `x` and it does nothing. 

![NoClear](https://user-images.githubusercontent.com/181089/192441585-cb2700a5-3b1a-4e32-9c71-0dfbe152021e.gif)

_Originally posted by @blackfalcon in https://github.com/AlaskaAirlines/auro-combobox/issues/90#issuecomment-1259005353_

**Comment by blackfalcon** [comment]
Reference: https://github.com/AlaskaAirlines/auro-combobox/pull/90

**Comment by jason-capsule42** [comment]
Unable to reproduce this issue.

**Comment by blackfalcon** [comment]
Issue is no longer repeatable.
