### ISSUE TITLE
input type validatation (e.g. date) is running while the date picker has focus.

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-combobox#97]
## Describe the bug

input `type` validatation (e.g. date) is running while the date picker has focus.

## To Reproduce

1. Go to 'http://auro.alaskaair.com/components/auro/combobox
1. Scroll to the type example that uses date format
1. Focus the input
1. Enter `1`
1. See error

## Expected behavior

The type validation should not be run while the datepicker has focus.

This looks like it may be an issue with auro-input specifically not with combobox.

**Comment by blackfalcon** [comment]
What is the actual error with this that is being addressed? What is the impact on the UI?
